################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
CPP_UPPER_SRCS := 
C++_UPPER_SRCS := 
CC_UPPER_SRCS := 
CPP_SRCS := 
O_SRCS := 
ELF_SRCS := 
CXX_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
CXX_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
C++_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
CC_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
CC_UPPER_DEPS := 
C++_UPPER_DEPS := 
CPP_UPPER_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
JMP_UPPER_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
CXX_DEPS := 
LIBRARY_GENERATOR_OUTPUTTYPE_OUTPUTS := 
JMP_DEPS := 
CXX_UPPER_DEPS := 
P_UPPER_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
PP_DEPS := 
CC_DEPS := 
SX_DEPS := 
C++_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
S_UPPER_DEPS := 
CPP_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
generate/compiler/asm \
generate/compiler/init \
generate/configuration \
generate/drivers/r_cache/src/lld \
generate/drivers/r_cpg/src/hld \
generate/drivers/r_cpg/src/lld \
generate/drivers/r_gpio/src/hld \
generate/drivers/r_gpio/src/lld \
generate/drivers/r_intc/src/lld \
generate/drivers/r_mmu/src/lld \
generate/drivers/r_stb/src/lld \
generate/gr_mango_boot \
generate \
generate/os_abstraction/src \
generate/sc_drivers/r_adc/src/hld \
generate/sc_drivers/r_adc/src/lld \
generate/sc_drivers/r_cbuffer/src \
generate/sc_drivers/r_ceu/src \
generate/sc_drivers/r_ceu/userdef \
generate/sc_drivers/r_drp/src \
generate/sc_drivers/r_drp_custom/drp_lib_custom/r_drp_bayer2lrgb/asm \
generate/sc_drivers/r_drp_custom/drp_lib_custom/r_drp_bayer2lrgb_color_correction/asm \
generate/sc_drivers/r_drp_custom/drp_lib_custom/r_drp_find_contours_crop/asm \
generate/sc_drivers/r_drp_custom/drp_lib_custom/r_drp_lrgb2l_gaussian_blur/asm \
generate/sc_drivers/r_drp_custom/drp_lib_custom/r_drp_lrgb2lcrop/asm \
generate/sc_drivers/r_drp_custom/drp_lib_custom/r_drp_resize_bilinear_crop/asm \
generate/sc_drivers/r_mipi/src \
generate/sc_drivers/r_mipi/userdef \
generate/sc_drivers/r_octabus/src/lld \
generate/sc_drivers/r_ostm/src/hld \
generate/sc_drivers/r_ostm/src/lld \
generate/sc_drivers/r_riic/src/hld \
generate/sc_drivers/r_riic/src/lld \
generate/sc_drivers/r_rvapi/src \
generate/sc_drivers/r_scifa/src/hld \
generate/sc_drivers/r_scifa/src/lld \
generate/sc_drivers/r_vdc/src \
generate/sc_drivers/r_vdc/userdef \
generate/system \
src/FreeRTOS \
src/FreeRTOS/portable/GCC/ARM_CA9_RZA2M \
src \
src/neural_networks/Translator \
src/neural_networks/tensorflow_lite/TF_lite_float \
src/neural_networks/tensorflow_lite/TF_lite_post_training_quantization \
src/neural_networks/tensorflow_lite/TF_lite_quantization_aware_training \
src/neural_networks/tensorflow_lite \
src/renesas/application/GR_MANGO/src \
src/renesas/application/common/camera \
src/renesas/application/common/console \
src/renesas/application/common/perform \
src/renesas/application/common/port_settings \
src/renesas/application/common/render \
src/renesas/application \
src/renesas/hwsetup \
src/renesas/hwsetup/octabus_setup/src \
src/tensorflow_lite \
src/tensorflow_lite/tensorflow/lite/c \
src/tensorflow_lite/tensorflow/lite/core/api \
src/tensorflow_lite/tensorflow/lite/kernels/internal \
src/tensorflow_lite/tensorflow/lite/kernels \
src/tensorflow_lite/tensorflow/lite/micro \
src/tensorflow_lite/tensorflow/lite/micro/kernels \
src/tensorflow_lite/tensorflow/lite/micro/kernels/cmsis_nn \
src/tensorflow_lite/tensorflow/lite/micro/memory_planner \
src/tensorflow_lite/tensorflow/lite/schema \
src/tensorflow_lite/third_party/cmsis/CMSIS/NN/Source/ActivationFunctions \
src/tensorflow_lite/third_party/cmsis/CMSIS/NN/Source/BasicMathFunctions \
src/tensorflow_lite/third_party/cmsis/CMSIS/NN/Source/ConcatenationFunctions \
src/tensorflow_lite/third_party/cmsis/CMSIS/NN/Source/ConvolutionFunctions \
src/tensorflow_lite/third_party/cmsis/CMSIS/NN/Source/FullyConnectedFunctions \
src/tensorflow_lite/third_party/cmsis/CMSIS/NN/Source/NNSupportFunctions \
src/tensorflow_lite/third_party/cmsis/CMSIS/NN/Source/PoolingFunctions \
src/tensorflow_lite/third_party/cmsis/CMSIS/NN/Source/ReshapeFunctions \
src/tensorflow_lite/third_party/cmsis/CMSIS/NN/Source/SVDFunctions \
src/tensorflow_lite/third_party/cmsis/CMSIS/NN/Source/SoftmaxFunctions \
src/tensorflow_lite/third_party/gemmlowp \
src/user_prog \

